- name: Enable Flathub repo
  become: yes
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Disable Fedora repo
  become: yes
  community.general.flatpak_remote:
    name: 
    - fedora
    - fedora-testing
    state: absent
  when: ansible_distribution == "Fedora"

- name: Install flatpak apps
  community.general.flatpak:
    name: 
    - md.obsidian.Obsidian
    - com.discordapp.Discord
    - org.gnome.gThumb
    - org.gimp.GIMP
    - org.remmina.Remmina
    - hu.irl.cameractrls
    - com.moonlight_stream.Moonlight
    - com.github.maoschanz.drawing
    - com.github.tchx84.Flatseal
    - com.github.zocker_160.SyncThingy
    - com.heroicgameslauncher.hgl
    - org.signal.Signal
    - com.mattjakeman.ExtensionManager
    - com.github.maoschanz.drawing
    - org.gtk.Gtk3theme.Adwaita-dark
  when: ansible_distribution != "openSUSE Tumbleweed" # not if rolling distrib

- name: Force Gtk Adwaita Dark theme
  become: yes
  command: flatpak override --env=GTK_THEME=Adwaita-dark


